✨ | [v3.1] Taxation Features, Advanced Logging & more features. #20
NamVr/Chat-Economy-Bot pull request #21
Opened 2023-08-12 18:15 UTC by NamVr

This PR is for v3.1.0 for NCE (Chat-Economy-Bot) to make improvements and add new features.

2023-08-27 13:55 UTC, NamVr commented
Logging is almost done (70%)! Hopeful release will be tomorrow :)

2023-08-28 13:05 UTC, NamVr commented
90% just implementation is left.

2023-09-16 18:01 UTC, NamVr commented
My current work is pushed, I have still not figured out the part of comparing two databases together, that is the only remaining part!
I appreciate any contributions :)

2023-09-17 21:07 UTC, StormPacer commented
Object comparer works, fixed an issue with currency and logging setup should follow the example in currency.js

2023-09-19 17:20 UTC, NamVr commented
Tyvm, need to do some basic type corrections and just need to add timezone based streak command instead of +24 hour /daily.

2023-09-25 12:04 UTC, nngggaming requested changes, later dismissed
### Grammatical Error
- File path: `interactions/slash/misc/currency.js`
- Lines: 145 to 147

Issue
- If `subCommand` is equal to `'remove'`, the following will be set as the embed description: 
> You have successfully removed [amount] [emoji] [name] to [user]

Fix
- The word 'to' should be changed to 'from':
> You have successfully removed [amount] [emoji] [name] from [user]
- Requested fix: https://pastebin.com/WB5rwxG9 (lines 145 to 147)

2023-12-15 18:27 UTC, NamVr commented
Thank you @nngggaming for suggestions, I will look into this ASAP.

2024-07-18 10:37 UTC, NamVr commented
I will be removing logging features from v3.1 due to them not being completed, will finish these things later (v3.2)!

Feats for v3.1 will be:
- Taxes! Transfers can now have taxes!
- Admins can now generate currency with admin management commands (`/currency`)
- BREAKING change in search and work command variables!
- Fixed some typos/grammar.

2025-10-21 16:37 UTC, Maghish approved these changes

2025-10-21 16:38 UTC, merged